Repository miniRT-jiphyeonjeon/MiniRT, pull requests merged in 2022-03, with the labels that each got.

#8 feat: :sparkles: Add [atof, isdigit, isspace] to [libft].
  lib/libft/Makefile
  lib/libft/include/ft_ascii.h
  lib/libft/include/libft.h
  lib/libft/src/ascii/ft_atof.c
  lib/libft/src/ascii/ft_isdigit.c
  lib/libft/src/ascii/ft_isspace.c
Labels: Feature ⭐

#13 structure.h 생성 및 3차원 벡터 연산 함수 구현
  Makefile
  include/minirt.h
  include/structure.h
  include/vector3.h
  src/event/hook_key_n_exit.c
  src/main.c
  src/vector3/vector_operation1.c
  src/vector3/vector_operation2.c
  src/vector3/vector_operation3.c
  src/vector3/vector_set.c
Labels: Feature ⭐

#17 feat: :sparkles: Add obj_list
  Makefile
  include/structure.h
  lib/libft/Makefile
  lib/libft/include/ft_string.h
  lib/libft/src/ascii/ft_atof.c
  lib/libft/src/string/ft_split.c
  lib/libft/src/string/ft_strcmp.c
  lib/libft/src/string/ft_strlcpy.c
  src/list/list_utils.c
Labels: Feature ⭐

#18 mlx window에 기본 이미지 띄우기
  Makefile
  include/event.h
  include/scene.h
  include/structure.h
  include/trace.h
  include/vector3.h
  src/event/draw.c
  src/event/draw_util.c
  src/main.c
  src/scene/scene.c
  src/trace/ray.c
  src/vector3/vector_set.c
Labels: Feature ⭐

#22 sphere, phong illumination model, hard shadow 구현
  Makefile
  include/scene.h
  include/structure.h
  include/trace.h
  src/event/draw.c
  src/main.c
  src/scene/object.c
  src/scene/scene.c
  src/trace/hit.c
  src/trace/hit_sphere.c
  src/trace/phong_illumination.c
  src/trace/phong_light.c
  src/trace/ray.c
Labels: Feature ⭐

#28 cylinder, plane 구현
  Makefile
  include/structure.h
  include/trace.h
  src/trace/hit.c
  src/trace/hit_cylinder.c
  src/trace/hit_plane.c
  src/trace/hit_sphere.c
  src/trace/util.c
  test1.rt
Labels: Feature ⭐

#34 그림자 오류 수정
  include/trace.h
  src/trace/hit_plane.c
  src/trace/phong_illumination.c
  src/trace/phong_light.c
  test1.rt
Labels: Bug 🐛

#35 카메라 방향벡터 오류 수정
  src/scene/camera.c
  test1.rt
Labels: Bug 🐛

#37 style: :lipstick: Add t_parse_list, change func name about parse
  Makefile
  include/parse.h
  include/structure.h
  lib/libft/src/ascii/ft_atof.c
  src/event/draw.c
  src/main.c
  src/parse/parse_bool.c
  src/parse/parse_to_element.c
  src/parse/parse_to_str.c
  src/parse/parse_utils.c
  src/scene/ambient.c
  src/scene/camera.c
  src/scene/light.c
  src/scene/objects.c
Labels: Feature ⭐, Refactor ⚙️
