Repository miniRT-jiphyeonjeon/MiniRT, pull requests merged in 2022-04, with the labels that each got.

#44 🎉 Bonus 파트 시작!
  Makefile
  include_bonus/error_bonus.h
  include_bonus/event_bonus.h
  include_bonus/list_bonus.h
  include_bonus/parse_bonus.h
  include_bonus/scene_bonus.h
  include_bonus/structure_bonus.h
  include_bonus/trace_bonus.h
  include_bonus/vector3_bonus.h
  include_bonus/x11_events_bonus.h
  input/cjang.rt
  input/test1.rt
  input_bonus/cjang.rt
  input_bonus/test1.rt
  src_bonus/error/error_bonus.c
  src_bonus/event/draw_bonus.c
  src_bonus/event/draw_util_bonus.c
  src_bonus/event/hook_key_n_exit_bonus.c
  src_bonus/list/list_utils_bonus.c
  src_bonus/main_bonus.c
  src_bonus/parse/parse_bool_bonus.c
  src_bonus/parse/parse_read_bonus.c
  src_bonus/parse/parse_to_element_bonus.c
  src_bonus/parse/parse_to_num_bonus.c
  src_bonus/parse/parse_to_str_bonus.c
  src_bonus/parse/parse_utils_bonus.c
  src_bonus/scene/ambient_bonus.c
  src_bonus/scene/camera_bonus.c
  src_bonus/scene/light_bonus.c
  src_bonus/scene/objects_bonus.c
  src_bonus/scene/scene_bonus.c
  src_bonus/trace/hit_bonus.c
  src_bonus/trace/hit_cylinder_bonus.c
  src_bonus/trace/hit_plane_bonus.c
  src_bonus/trace/hit_sphere_bonus.c
  src_bonus/trace/phong_illumination_bonus.c
  src_bonus/trace/phong_light_bonus.c
  src_bonus/trace/ray_bonus.c
  src_bonus/trace/util_bonus.c
  src_bonus/vector3/vector_operation1_bonus.c
  src_bonus/vector3/vector_operation2_bonus.c
  src_bonus/vector3/vector_operation3_bonus.c
  src_bonus/vector3/vector_set_bonus.c
Labels: Feature ⭐

#49 Cjang/issue48 bonus struct fix
  include_bonus/event_bonus.h
  include_bonus/structure_bonus.h
  lib/libft/src/ascii/ft_atof.c
  src_bonus/list/list_utils_bonus.c
  src_bonus/scene/light_bonus.c
  src_bonus/scene/objects_bonus.c
  src_bonus/trace/hit_cylinder_bonus.c
  src_bonus/trace/hit_plane_bonus.c
  src_bonus/trace/hit_sphere_bonus.c
  src_bonus/trace/phong_light_bonus.c
Labels: Feature ⭐

#52 fix: :lipstick: Fix finding out of range and allowing property.
  include/parse.h
  src/parse/parse_bool.c
  src/parse/parse_to_num.c
  src/parse/parse_to_str.c
  src/scene/objects.c
Labels: Bug 🐛

#53 feat: :sparkles: Add checkerboard parse
  include_bonus/parse_bonus.h
  include_bonus/structure_bonus.h
  src_bonus/list/list_utils_bonus.c
  src_bonus/parse/parse_bool_bonus.c
  src_bonus/parse/parse_to_num_bonus.c
  src_bonus/parse/parse_to_str_bonus.c
  src_bonus/parse/parse_utils_bonus.c
  src_bonus/scene/objects_bonus.c
Labels: Feature ⭐

#61 feat: :sparkles: Add bumpmap parse
  Makefile
  include_bonus/list_bonus.h
  include_bonus/parse_bonus.h
  include_bonus/scene_bonus.h
  include_bonus/structure_bonus.h
  input/.rt
  input/a.rt/cj.rt
  input_bonus/test1.rt
  src_bonus/list/list_del_bonus.c
  src_bonus/list/list_utils_bonus.c
  src_bonus/main_bonus.c
  src_bonus/parse/parse_to_element_bonus.c
  src_bonus/scene/objects_bonus.c
Labels: Feature ⭐

#64 Cjang/issue62 t object add
  Makefile
  include_bonus/scene_bonus.h
  include_bonus/structure_bonus.h
  include_bonus/trace_bonus.h
  src_bonus/parse/parse_bool_bonus.c
  src_bonus/parse/parse_to_element_bonus.c
  src_bonus/parse/parse_to_str_bonus.c
  src_bonus/scene/objects_bonus.c
  src_bonus/trace/hit_bonus.c
  src_bonus/trace/hit_cone_bonus.c
  src_bonus/trace/hit_cylinder_bonus.c
  src_bonus/trace/hit_plane_bonus.c
  src_bonus/trace/hit_sphere_bonus.c
Labels: Feature ⭐

#66 feat: :sparkles: Add light parse more than one
  src_bonus/parse/parse_bool_bonus.c
  src_bonus/parse/parse_to_str_bonus.c
  src_bonus/trace/hit_cone_bonus.c
Labels: Feature ⭐

#72 Cjang/issue69 add texture only
  include_bonus/structure_bonus.h
  include_bonus/trace_bonus.h
  src_bonus/list/list_del_bonus.c
  src_bonus/parse/parse_bool_bonus.c
  src_bonus/parse/parse_to_str_bonus.c
  src_bonus/scene/objects_bonus.c
  src_bonus/trace/image_mapping_bonus.c
Labels: Feature ⭐

#90 Cjang/issue77/parse exception check
  lib/libft/Makefile
  lib/libft/include/ft_string.h
  lib/libft/src/string/ft_strsep.c
  src/parse/parse_to_str.c
  src_bonus/parse/parse_str_set_bonus.c
  src_bonus/parse/parse_to_num_bonus.c
  src_bonus/parse/parse_to_str_bonus.c
Labels: Bug 🐛

#100 Cjang/issue80/parse error fix bonus
  Makefile
  include_bonus/parse_bonus.h
  include_bonus/structure_bonus.h
  lib/libft/src/ascii/ft_atof.c
  src_bonus/main_bonus.c
  src_bonus/parse/parse_str_get_bonus.c
  src_bonus/parse/parse_str_set_bonus.c
  src_bonus/parse/parse_to_num_bonus.c
  src_bonus/parse/parse_to_str_bonus.c
Labels: Bug 🐛

#103 Cjang/issue80/parse error fix
  include/parse.h
  include_bonus/parse_bonus.h
  lib/libft/Makefile
  lib/libft/include/ft_ascii.h
  lib/libft/src/ascii/ft_atof.c
  lib/libft/src/ascii/ft_atoi.c
  src/parse/parse_to_num.c
  src/scene/ambient.c
  src/scene/camera.c
  src/scene/light.c
  src/scene/objects.c
  src_bonus/parse/parse_str_get_bonus.c
  src_bonus/parse/parse_to_num_bonus.c
  src_bonus/scene/ambient_bonus.c
  src_bonus/scene/camera_bonus.c
  src_bonus/scene/light_bonus.c
  src_bonus/scene/objects_bonus.c
Labels: Bug 🐛

#105 42 Header 붙이기 + norm 점검
  Makefile
  include/event.h
  include/structure.h
  include/trace.h
  include/vector3.h
  include/x11_events.h
  include_bonus/event_bonus.h
  include_bonus/structure_bonus.h
  include_bonus/trace_bonus.h
  include_bonus/vector3_bonus.h
  include_bonus/x11_events_bonus.h
  src/event/draw.c
  src/event/draw_util.c
  src/event/hook_key_n_exit.c
  src/main.c
  src/trace/hit.c
  src/trace/hit_cylinder.c
  src/trace/hit_plane.c
  src/trace/hit_sphere.c
  src/trace/phong_illumination.c
  src/trace/phong_light.c
  src/trace/ray.c
  src/trace/util.c
  src/vector3/vector_operation1.c
  src/vector3/vector_operation2.c
  src/vector3/vector_operation3.c
  src/vector3/vector_set.c
  src_bonus/event/draw_bonus.c
  src_bonus/event/draw_util_bonus.c
  src_bonus/event/hook_key_n_exit_bonus.c
  src_bonus/main_bonus.c
  src_bonus/trace/hit_bonus.c
  src_bonus/trace/hit_cone_bonus.c
  src_bonus/trace/hit_cylinder_bonus.c
  src_bonus/trace/hit_plane_bonus.c
  src_bonus/trace/hit_sphere_bonus.c
  src_bonus/trace/image_mapping_bonus.c
  src_bonus/trace/phong_illumination_bonus.c
  src_bonus/trace/phong_light_bonus.c
  src_bonus/trace/ray_bonus.c
  src_bonus/trace/texture_bonus.c
  src_bonus/trace/util_bonus.c
  src_bonus/vector3/vector_matrix_bonus.c
  src_bonus/vector3/vector_operation1_bonus.c
  src_bonus/vector3/vector_operation2_bonus.c
  src_bonus/vector3/vector_operation3_bonus.c
  src_bonus/vector3/vector_set_bonus.c
Labels: Refactor ⚙️

#108 feat: :sparkles: Add coordinate_system for mandatory part
  include/event.h
  include/structure.h
  include/vector3.h
  src/scene/camera.c
  src/vector3/vector_operation1.c
  src/vector3/vector_operation3.c
  src/vector3/vector_set.c
Labels: Refactor ⚙️

#110 refactor: :recycle: Update camera orientation vector
  input/cjang.rt
  input/test1.rt
  input_bonus/cjang.rt
  input_bonus/miniearth.rt
  input_bonus/test1.rt
  input_bonus/test2.rt
  miniearth.c
  src/scene/camera.c
  src_bonus/scene/camera_bonus.c
Labels: Refactor ⚙️
